新增：额度限制
lss233/chatgpt-mirai-qq-bot pull request #180
Opened 2023-02-21 19:27 UTC by lss233

2023-02-22 05:02 UTC, BlueGlassBlock requested changes

2023-02-22 05:02 UTC, BlueGlassBlock commented on bot.py
> +async def update_rate(sender: Union[Friend, Member], type: str, id: str, rate: int):
建议获取 `event: MessageEvent` `app: Ariadne` 对事件类型判断后操作

以及仍然需要通过 `app.send_message(event, ...)` 发送消息

2023-02-22 10:05 UTC, BlueGlassBlock approved these changes

2023-02-22 10:23 UTC, lss233 commented
但是这代码还是不对劲。  commander 那边捕获了事件后，前面 ChatGPT 的两个方法也收到了事件。  
打断事件传递的方式不对？

2023-02-26 01:55 UTC, VarPower1989 commented
怎么将限制增加到现有服务器中😳

2023-02-26 01:56 UTC, VarPower1989 commented
能不能对群里的没人提问进行限制次数

2023-02-27 00:56 UTC, lss233 commented
> 怎么将限制增加到现有服务器中😳

合并进去之后就可以了

2023-02-27 00:59 UTC, merged