Adding Markdown Support.
lss233/chatgpt-mirai-qq-bot pull request #188
Opened 2023-02-23 13:53 UTC by Hakureirm

This PR includes changes to add Markdown support to 'text_to_img.py' and update the Dockerfile, as well as changes to the apt installation file and pip requirements file and font files. All changes have been successfully tested in Docker.

2023-02-23 14:01 UTC, lss233 requested changes

2023-02-23 14:01 UTC, lss233 commented on utils/markdown_support_template.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/3.0.1/github-markdown.min.css">
能不加载远程资源的话就尽量避免吧，要不然渲染一次就得多花一点时间。  还要考虑网络异常的情况。

2023-02-23 14:01 UTC, lss233 commented on Dockerfile
> +RUN cp ./fonts/sarasa-mono-sc-regular.ttf /usr/share/fonts/
容器启动时要再执行一次复制字体，否则无法支持用户自定义的字体

2023-02-23 17:22 UTC, lss233 commented
在 Windows 下启动出现如下报错：
```
D:\quickstart-windows-amd64\chatgpt\python3.9\python.exe D:\quickstart-windows-amd64\chatgpt-mirai-qq-bot\bot.py 
Traceback (most recent call last):
  File "D:\quickstart-windows-amd64\chatgpt-mirai-qq-bot\bot.py", line 26, in <module>
    from utils.text_to_img import to_image
  File "D:\quickstart-windows-amd64\chatgpt-mirai-qq-bot\utils\text_to_img.py", line 6, in <module>
    import markdown
  File "D:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\markdown\__init__.py", line 22, in <module>
    from .core import Markdown, markdown, markdownFromFile
  File "D:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\markdown\core.py", line 27, in <module>
    from .preprocessors import build_preprocessors
  File "D:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\markdown\preprocessors.py", line 29, in <module>
    from .htmlparser import HTMLExtractor
  File "D:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\markdown\htmlparser.py", line 31, in <module>
    spec.loader.exec_module(htmlparser)
AttributeError: 'zipimporter' object has no attribute 'exec_module'
2023-02-24 01:12:44.213 | INFO     | chatbot:conversation_remover:101 - 删除会话中……

Process finished with exit code 1

```

2023-02-24 03:34 UTC, acai66 commented on utils/text_to_img.py
> +    image1 = imgkit.from_file(filename="./utils/temp.html",  config=config, options=options, output_path="temp.jpg")
> 这里应该要用临时文件，否则在遇到多线程时会有冲突的可能性。

我尝试使用临时文件来存储html与jpg，功能上测试没问题，就是html转图片的函数执行时间很长。
```
def text_to_image(text):
    
    content = md_to_html(text)
    
    image = None
    
    # 输出html到字符串io流
    with StringIO() as output_file:
        with open('./utils/markdown_support_template.html', 'r') as input_file:
        
            for line in input_file:
                if "{{ md_to_html(text) }}" in line:
                    line = line.replace("{{ md_to_html(text) }}", content)
                output_file.write(line)

   
       # wkhtmltoimage是用apt安装的，安装wkhtmltopdf附带，binary文件在/usr/bin/wkhtmltoimage
        config = imgkit.config(wkhtmltoimage='/usr/bin/wkhtmltoimage')

        options = {
            "enable-local-file-access": None, # wkhtmltoimage默认禁用local，所以需要开启读取local文件的权限
            "width": 500 # 图片宽度
        }
        
        # 创建临时jpg文件
        temp_jpg_file = NamedTemporaryFile(mode='w+b', suffix='.jpg', delete=False)
        temp_jpg_filename = temp_jpg_file.name
        temp_jpg_file.close()
        
        with StringIO(output_file.getvalue()) as input_file:
            # 调用imgkit将html转为图片
            image1 = imgkit.from_file(filename=input_file,  config=config, options=options, output_path=temp_jpg_filename)

        # 调用PIL将图片读取为PNG，RGB格式
        image = Image.open(temp_jpg_filename, formats=['JPEG']).convert('RGB')
        
        # 删除临时文件
        if os.path.exists(temp_jpg_filename):
            os.remove(temp_jpg_filename)

    return image
```

2023-02-24 05:06 UTC, acai66 commented
询问markdown语法时，有这一段图片样例，在渲染为html时报错：提示`图片URL`加载失败
![image](https://user-images.githubusercontent.com/37766207/221096534-2f0b8065-9d32-473e-a94b-b69b0761fb58.png)

2023-02-24 05:42 UTC, acai66 commented
保险起见，又加入了之前的`text_to_image`函数，在markdown渲染失败时，调用之前的文本转图片函数。
![image](https://user-images.githubusercontent.com/37766207/221101011-552adeaa-10e2-4954-8268-253afd53c45a.png)

2023-02-24 06:02 UTC, lss233 commented
> 保险起见，又加入了之前的`text_to_image`函数，在markdown渲染失败时，调用之前的文本转图片函数。 ![image](https://user-images.githubusercontent.com/37766207/221101011-552adeaa-10e2-4954-8268-253afd53c45a.png)

我觉得这样很不错

2023-02-24 07:00 UTC, acai66 commented
供参考，不提pr
[text_to_img.zip](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10821437/text_to_img.zip)

2023-02-24 09:19 UTC, lss233 commented
> 供参考，不提pr [text_to_img.zip](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10821437/text_to_img.zip)

好的，那就由我来进行一个合并

2023-02-24 13:18 UTC, lss233 commented
搞定了，感谢两位

2023-02-24 13:19 UTC, merged

2023-02-24 15:36 UTC, acai66 commented
不清楚你们有没有单行代码过长被截断的情况
![4ea5213713078d87](https://user-images.githubusercontent.com/37766207/221219886-e746a264-da4a-4206-b89a-9b267fbfffb6.png)

2023-02-24 16:39 UTC, Hakureirm commented
> 不清楚你们有没有单行代码过长被截断的情况 ![4ea5213713078d87](https://user-images.githubusercontent.com/37766207/221219886-e746a264-da4a-4206-b89a-9b267fbfffb6.png)

出现过。代码块应该是可以改成超出原设定宽度后，自适应宽度的，之前测试它自己渲染来自URL的图片时就自动做到了，不过我没学过前端，不知道具体是改哪里。

2023-02-24 17:11 UTC, lss233 commented
这个开个 issue 跟一下