添加微信支持
lss233/chatgpt-mirai-qq-bot pull request #448
Opened 2023-03-28 06:19 UTC by shyu216

- 利用的是itchat，运行后扫二维码登录，可短暂记住账号密码，保存在itchat.pkl中

- 暂无config.cfg功能实现

- 依赖在requirement_wechat里面

- 目前可以用这个运行
cd chatgpt && python3.11\python.exe itchat-bot.py

2023-03-28 06:27 UTC, shyu216 commented
嗷目前有两个小bug

- 扫二维码要扫五六次才能成功

- 不正常退出就保存不了pkl

2023-03-28 06:36 UTC, lss233 requested changes
感谢你的 PR！请不要忘记了在 README.md 中补充你所加入的功能的介绍。

2023-03-28 06:36 UTC, lss233 commented on platforms/itchat-bot.py
> +# 如果加到bot.py里面，就不需要这两行了
你可以参考 bot.py，在那边统一启动。

2023-03-28 06:36 UTC, lss233 commented on config.wechat.example.cfg
> +[itchat]
我觉得不需要分成多个配置文件，要不然不好管理，改动很大。

2023-03-28 06:36 UTC, lss233 commented on platforms/itchat-bot.py
> +    loginCallback = init_data
我们对变量使用 snake_case 命名风格。

2023-03-28 06:36 UTC, lss233 commented on platforms/itchat-bot.py
> +            logger.info('此微信号不能登录网页版微信，不能运行此项目。没有任何其它解决办法！可以换个号再试试。')
对于严重错误，请使用 `logger.error(...)`。对于异常，使用 `logger.exception(...)`

2023-03-28 06:36 UTC, lss233 commented on requirement_wechat.txt
> +itchat-uos==1.5.0.dev
可以合并到 requirements.txt

2023-03-28 06:36 UTC, lss233 commented on platforms/itchat-bot.py
> +    is_manager = False
**TODO**: 兼容触发词系统

2023-03-28 06:36 UTC, lss233 commented on platforms/itchat-bot.py
> +    logger.info(msg.fromUserName+':'+msg.text)
TODO: 兼容触发词系统

2023-03-28 06:36 UTC, lss233 commented on platforms/itchat-bot.py
> +        if len(request_list)>0:
为什么要用一个队列来管理所有的聊天消息？ 这样会导致程序一次只能回复一个人。

2023-03-28 07:15 UTC, shyu216 commented on platforms/itchat-bot.py
> +        if len(request_list)>0:
那个itchat接收消息的function是sync的，但是我们的handle_message是async的，我不知道怎么办。。。

2023-03-28 07:18 UTC, shyu216 commented on platforms/itchat-bot.py
> +            logger.info('此微信号不能登录网页版微信，不能运行此项目。没有任何其它解决办法！可以换个号再试试。')
好的

2023-03-28 07:18 UTC, shyu216 commented on platforms/itchat-bot.py
> +    loginCallback = init_data
好的

2023-03-28 07:19 UTC, shyu216 commented on config.wechat.example.cfg
> +[itchat]
好的

2023-03-28 07:19 UTC, shyu216 commented on platforms/itchat-bot.py
> +# 如果加到bot.py里面，就不需要这两行了
好的

2023-03-28 07:19 UTC, shyu216 commented on requirement_wechat.txt
> +itchat-uos==1.5.0.dev
好的

2023-03-28 11:28 UTC, shyu216 commented
> 说起来这个容易封号吗

有道理，我找了一下，好像确实有这样的案例：https://github.com/AutumnWhj/ChatGPT-wechat-bot/issues/158

但我用了两天，暂时还没有被封的迹象。。。

2023-03-29 02:18 UTC, lss233 commented
根据我的了解，itchat 已经停止维护了……

2023-03-29 02:39 UTC, shyu216 commented
> 根据我的了解，itchat 已经停止维护了……

确实，大佬有什么建议吗

那个还在维护的wechaty是js的，我不太懂怎么和python拼在一起。。。

2023-03-29 03:00 UTC, lss233 commented
这方面我也不是很懂。Wechaty 似乎是收费的，免费的方案也是使用 Web 协议登录，和 itchat 基本上一样。
或许可以看看 https://juejin.cn/post/7179140844073680954  
我找到的 Hook 方案的框架：https://gitee.com/qxvxhook/pc-vx-hook-http-api

2023-03-29 06:00 UTC, shyu216 commented
> 这方面我也不是很懂。Wechaty 似乎是收费的，免费的方案也是使用 Web 协议登录，和 itchat 基本上一样。
> 或许可以看看 https://juejin.cn/post/7179140844073680954
> 我找到的 Hook 方案的框架：https://gitee.com/qxvxhook/pc-vx-hook-http-api

感谢大佬，我觉得我可以放弃了，哈哈

微信太坏了。。。

2023-03-29 06:01 UTC, closed without merging

2023-04-12 09:10 UTC, RickyLoveFreedom commented
可以试下这个，https://github.com/billyplus/ntchat.git  目前还不错

2023-05-09 02:45 UTC, wenxie18 commented
ntchat没有 mac版本