feat: initial process and presets
lss233/chatgpt-mirai-qq-bot pull request #45
Opened 2022-12-13 12:17 UTC by 1847905557

* 支持在新建session或重置session的时候自动往 ChatGPT 里倒一些初始化内容
* 支持通过关键词自动往 ChatGPT 里倒一些预设内容
* 调整一些变量名并稍微整理代码格式
* 修缮 README
* 更新 requirements

2022-12-13 13:20 UTC, 1847905557 commented
不过现在 ChatGPT 网络好像很寄，不太建议现在使用初始化

2022-12-13 14:12 UTC, 1847905557 commented
修好conflict了（悲

2022-12-13 17:47 UTC, lss233 commented
非常感谢！

给我点时间处理一下

2022-12-13 21:15 UTC, lss233 requested changes

2022-12-13 21:15 UTC, lss233 commented on bot.py
> +        await chatbot.initial_process(app, target, session)
这个时候， `timeout_task` 应该还在运行中吧，到时候会出现正在进行预设加载，同时又发送 `response.timeout_format` 的情况

2022-12-13 21:15 UTC, lss233 commented on chatbot.py
> +    event = await app.send_message(target, '加载人设完毕')
是希望用户以修改代码的方式实现吗？  
或许可以通过配置文件来设置？  
出现异常该怎么办？

2022-12-14 06:33 UTC, 1847905557 commented on chatbot.py
> +    event = await app.send_message(target, '加载人设完毕')
希望用户修改代码，目前来说通过配置文件可能自定义程度难以达到要求
异常部分，有个很绿皮的想法是直接把bot.py的try:挪到更上方，但不太清楚这样是否合它的本意

2023-01-01 15:57 UTC, lss233 approved these changes

2023-01-02 15:04 UTC, merged