Support VITS and improve baiducloud performance
lss233/chatgpt-mirai-qq-bot pull request #460
Opened 2023-03-29 15:42 UTC by Haibersut

在做的
- [x] VITS_API版本支持（基于[MoeGoe](https://github.com/Artrajz/MoeGoe-Simple-API))
- [ ] VITS语音异常处理
- [ ] 百度云过期token处理

已知迷之bug：

发几条语音后会触发计时器
```
2023-03-29 23:15:03.826 | INFO     | graia.ariadne.model:log:82 - 1518503928: [SEND][233(323027561)] <- 会话已重置。
文件已保存到：data\voice\output_2023-03-29_23-15-08.ogg
2023-03-29 23:15:09.672 | INFO     | graia.ariadne.model:log:82 - 1518503928: [SEND][233(323027561)] <- [语音]
2023-03-29 23:15:09.679 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
```

2023-03-29 23:42 UTC, lss233 requested changes

2023-03-29 23:42 UTC, lss233 commented on config.py
> +    vits: bool = False
这里改成engine: str吧，然后从vits和azure两个选。

2023-03-29 23:42 UTC, lss233 commented on universal.py
> +        async def tts_process_element(elem, conversation_context):
可以整理到一个专门的文件里面。堆在这里看着太乱了

2023-03-29 23:42 UTC, lss233 commented on vits.py
> +    base_url = 'http://127.0.0.1'
需要使用配置文件来设置这些信息

2023-03-29 23:42 UTC, lss233 commented on vits.py
> +    id = 3
这个应该是音色吧

2023-04-01 09:37 UTC, Haibersut commented
目前能想到的都整完了，待进一步测试

2023-04-01 11:41 UTC, merged