support http service.
lss233/chatgpt-mirai-qq-bot pull request #518
Opened 2023-04-03 03:33 UTC by lcjqyml

support http service.

2023-04-03 08:02 UTC, lss233 commented
有没有在多端并发实测过？ 我在队列中使用的是 asyncio.Lock，如果每个聊天平台都是一个专门的 event loop，这种锁可能会失效。

2023-04-03 08:22 UTC, lcjqyml commented
同时启动了mirai和http两个模式，分别请求确实没问题，不过你说的场景，同时发送就出错了。还有个情况，刚隔了半个多小时请求yiyan，就提示 RuntimeError: Event loop is closed
没玩过python的多线程高并发，抓瞎了…

2023-04-03 12:35 UTC, lcjqyml commented
我把主线程的 event loop 设置给了 各个子线程。并发请求没出错了。已push。

2023-04-03 13:59 UTC, lss233 requested changes

2023-04-03 14:03 UTC, lss233 requested changes

2023-04-03 14:03 UTC, lss233 commented on platforms/onebot_bot.py
> +        asyncio.set_event_loop(event_loop)
```suggestion
def main(event_loop=asyncio.get_event_loop()):
    asyncio.set_event_loop(event_loop)
```

2023-04-03 14:03 UTC, lss233 commented on platforms/http_service.py
> +        loop = asyncio.get_event_loop()
可以参考 onebot_bot.py 进行简化

2023-04-03 16:57 UTC, lss233 commented
感谢您的 PR！

2023-04-03 16:57 UTC, merged

2023-04-04 01:00 UTC, lcjqyml commented
运行一段时间后，还是出现异常：RuntimeError: Event loop is closed