fix(llm): bing livecheck
lss233/chatgpt-mirai-qq-bot pull request #818
Opened 2023-05-15 03:51 UTC by WangEdward

2023-05-15 03:58 UTC, WangEdward commented on framework/llm/microsoft/models.py
> +        bot = await EdgeChatbot.create(cookies=json.loads(self.cookie_content))
不是很确定是否可以吧这个 Object 直接存在 `BingCookieAuth` 里，以减少 `bing.py` 可能有的多次创建？https://github.com/lss233/chatgpt-mirai-qq-bot/blob/5a6f90b409509d373fb3733324061317d650448a/framework/llm/microsoft/bing.py#L37-L42

2023-05-15 09:17 UTC, lss233 requested changes

2023-05-15 09:17 UTC, lss233 commented on framework/llm/microsoft/models.py
> +        bot = await EdgeChatbot.create(cookies=json.loads(self.cookie_content))
对话的上下文 conversationId 也存放在这个 bot 实例中。 如果共享 bot 实例，就不好隔离每个对话的 conversationId 了。

2023-05-15 09:17 UTC, lss233 commented on framework/llm/microsoft/models.py
> +        # cookie_content 的格式不可以直接作为 header，所以不能直接用 httpx 来测试
其实可以转换一下，像这样：
```python
';'.join(f"{cookie['name']}=cookie['value'])" for cookie in json.loads(self.cookie_content))
```

2023-05-15 09:17 UTC, lss233 commented on prompts/default_speak.yml
> +  - action: system/use-tts-engine
如果我们有一个变量可以表示 `constants.config.text_to_speech.always`，那就可以在这里加一个 `when` 条件来实现在只有在 true 的情况下才配置语音。  

这样，我们就不需要分出两个 default 预设了。

2023-05-15 09:17 UTC, lss233 commented on prompts/default.yml
>  supported_llms:
我们可以改成用 `'*'` 来表示任何 llm。

2023-05-15 14:31 UTC, lss233 requested changes
辛苦了！还有一些问题需要看一下……

2023-05-15 14:31 UTC, lss233 commented on framework/llm/microsoft/models.py
> -                trust_env=True,
`trust_env` 是必要的，用于设置代理。

2023-05-15 14:31 UTC, lss233 commented on framework/universal.py
> +            await request.conversation_context.load_preset(_prompt_name)
```suggestion
            await request.conversation_context.load_preset('default')
```

2023-05-15 14:31 UTC, lss233 commented on prompts/default.yml
> +    when: send_message
```suggestion
    when: tts_engine
```
当设置了 TTS 引擎时， 变量 `tts_engine` 会有值。  

refer:  
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/88c395d178cdc8c7cd7a5b72c4625266177e2caf/framework/conversation.py#L172-L175

2023-05-15 14:31 UTC, lss233 commented on prompts/default.yml
> +      text: ${{ output.message }}
这个其实是不必要的。

2023-05-15 14:31 UTC, lss233 commented on prompts/default.yml
>      args:
在默认预设中，我们也不会对输入字符串进行处理。

2023-05-15 14:54 UTC, WangEdward commented
好的，我明天来改

2023-05-15 15:11 UTC, WangEdward commented on framework/conversation.py
> +                text_to_speak = EmotionMarkupText([("neutral", text)])
Edge 里所用的 `EmotionMarkupText` 用 `str(text)` 处理过后使用的是 `str` 的格式（不含音色），所以是可以正常生成的。（你甚至还有写 Unit test 😂）`VITS` 我明天部署看一下

https://github.com/lss233/chatgpt-mirai-qq-bot/blob/538519e25a93fe5b58ba73e7c86b333eab59b7ec/framework/tts/edge.py#L33-L34

https://github.com/lss233/chatgpt-mirai-qq-bot/blob/538519e25a93fe5b58ba73e7c86b333eab59b7ec/framework/tts/tts.py#L98-L100

2023-05-16 02:21 UTC, WangEdward commented on framework/conversation.py
> +                text_to_speak = EmotionMarkupText([("neutral", text)])
这样应该也不会产生问题，现在的 Edge 和 Azure 都是可以正常跑的。VITS 目前没有代码，不过加一行把 neutral 替换为 0 应该就行了

2023-05-16 02:47 UTC, lss233 requested changes
默认预设可以删除非必要的处理流程

2023-05-16 03:03 UTC, WangEdward commented on prompts/default.yml
>      output: input.message
这里删了会报错 `TypeError: Object of type MessageChain is not JSON serializable`

2023-05-16 03:23 UTC, lss233 commented on prompts/default.yml
>      output: input.message
OK，那就先这样，我之后来改

2023-05-16 03:24 UTC, merged